[big]*i.     Abstract*

This document tries to come to a better understanding of the concept of “dataset”.

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, dataset, data set

[big]*iii.   Preface*

[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work. >
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====
[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* https://sdfe.dk/[Danish Agency for Data Supply and Efficiency (SDFE)]
* https://digst.dk/[Danish Agency for Digitisation (DIGST)]

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

|===
|Name |Affiliation

|Heidi Vanparys _(editor)_
|Danish Agency for Data Supply and Efficiency

|Anna Odgaard Ingram _(editor)_
|Danish Agency for Digitisation

|Ann Nyby Rennison
|Danish Agency for Data Supply and Efficiency

|Dorthe Kirstine Nordentoft
|Danish Agency for Data Supply and Efficiency

|Jan Hjelmager
|Danish Agency for Data Supply and Efficiency

|Lars Erik Storgaard
|Danish Agency for Data Supply and Efficiency

|Maya Borges
|Danish Agency for Digitisation

|Peter Bruhn Andersen
|Danish Agency for Digitisation

|===
